//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Package/VAT.Input/Runtime/Desktop/DesktopInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace VAT.Input.Desktop
{
    public partial class @DesktopInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @DesktopInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""DesktopInputActions"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""744695b2-b289-439b-ae55-47c3ec6d0362"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""d25c1806-11f6-47a9-bc92-31326231d0e6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""98e05abc-89be-42e6-a55d-20412f14fd56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""cfd4a371-228f-4de5-b470-5842b9d0da35"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Value"",
                    ""id"": ""64d55976-9c5f-4021-925b-e1caa0ce79c8"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""dea587af-0f09-4b07-a6d0-699812a7a43f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c3de7829-4ce8-40bc-80f1-48c884dcfaf4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""eed65052-241a-4eb9-89d5-d138771c6883"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8298a817-d1e6-4ec0-8fe3-5a0cc5ac0a6e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0fc687c7-b440-46a8-b9e7-99cb0b43b999"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""aa473c42-c13d-4a10-9751-a5239b9e005b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7532010-1377-4860-8d27-ac3b8dd3b219"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""83338ca5-4b56-473a-8c22-3d078346156e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6f649dc0-048f-442b-a9c3-38aea84b9400"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""414ab848-88df-4d67-9de8-32631be044f3"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""HandLeft"",
            ""id"": ""bb41bb27-9c25-4496-bb27-4c70647a4f99"",
            ""actions"": [
                {
                    ""name"": ""GripAxis"",
                    ""type"": ""Button"",
                    ""id"": ""21884fa6-2737-438f-846b-8456a3f5d39b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""cebf913e-7ae0-445e-ba17-214be041e58c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""030fb394-96b7-4f18-8636-f8f54dae227d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18e1b292-c90a-4f0f-b6d5-d521258050bd"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""HandRight"",
            ""id"": ""b6664450-66a1-4762-8dfb-d119a44908b1"",
            ""actions"": [
                {
                    ""name"": ""GripAxis"",
                    ""type"": ""Button"",
                    ""id"": ""efdfc0a6-c4ba-4705-8a99-eadc06f0f79e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbstickAxis"",
                    ""type"": ""Value"",
                    ""id"": ""844ab350-a2b0-4aa7-844e-5a25f0c5f070"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""02aa00c1-d8d3-4881-8851-765da07ed024"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerAxis"",
                    ""type"": ""Button"",
                    ""id"": ""ceee6804-5d75-4bbc-b850-66920c8ebb0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""74e2881d-88cb-4b3c-9077-2b88d058c054"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8d51b1d9-7d60-4269-9968-f86b563337f6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b6f86bc3-e3a9-4bbf-bd81-93c52d11b8c7"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""18633e65-95a7-4a0b-ab4e-614ffa1a7a15"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0a6b60fa-f48c-470c-9d80-677135a1adac"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3c7b338c-7e04-41a0-9ce5-26c8ec830ba4"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a44df0d4-c2f2-4b96-a2df-4bee7e4d9d9c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b16f9b1-3288-45fa-9e7d-dc1f5c0a89df"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Gameplay
            m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
            m_Gameplay_Movement = m_Gameplay.FindAction("Movement", throwIfNotFound: true);
            m_Gameplay_Jump = m_Gameplay.FindAction("Jump", throwIfNotFound: true);
            m_Gameplay_Look = m_Gameplay.FindAction("Look", throwIfNotFound: true);
            m_Gameplay_Crouch = m_Gameplay.FindAction("Crouch", throwIfNotFound: true);
            // HandLeft
            m_HandLeft = asset.FindActionMap("HandLeft", throwIfNotFound: true);
            m_HandLeft_GripAxis = m_HandLeft.FindAction("GripAxis", throwIfNotFound: true);
            m_HandLeft_SecondaryButton = m_HandLeft.FindAction("SecondaryButton", throwIfNotFound: true);
            // HandRight
            m_HandRight = asset.FindActionMap("HandRight", throwIfNotFound: true);
            m_HandRight_GripAxis = m_HandRight.FindAction("GripAxis", throwIfNotFound: true);
            m_HandRight_ThumbstickAxis = m_HandRight.FindAction("ThumbstickAxis", throwIfNotFound: true);
            m_HandRight_SecondaryButton = m_HandRight.FindAction("SecondaryButton", throwIfNotFound: true);
            m_HandRight_TriggerAxis = m_HandRight.FindAction("TriggerAxis", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Gameplay
        private readonly InputActionMap m_Gameplay;
        private IGameplayActions m_GameplayActionsCallbackInterface;
        private readonly InputAction m_Gameplay_Movement;
        private readonly InputAction m_Gameplay_Jump;
        private readonly InputAction m_Gameplay_Look;
        private readonly InputAction m_Gameplay_Crouch;
        public struct GameplayActions
        {
            private @DesktopInputActions m_Wrapper;
            public GameplayActions(@DesktopInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_Gameplay_Movement;
            public InputAction @Jump => m_Wrapper.m_Gameplay_Jump;
            public InputAction @Look => m_Wrapper.m_Gameplay_Look;
            public InputAction @Crouch => m_Wrapper.m_Gameplay_Crouch;
            public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
            public void SetCallbacks(IGameplayActions instance)
            {
                if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
                {
                    @Movement.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                    @Movement.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                    @Movement.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovement;
                    @Jump.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                    @Jump.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                    @Jump.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnJump;
                    @Look.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLook;
                    @Look.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLook;
                    @Look.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLook;
                    @Crouch.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCrouch;
                    @Crouch.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCrouch;
                    @Crouch.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCrouch;
                }
                m_Wrapper.m_GameplayActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Movement.started += instance.OnMovement;
                    @Movement.performed += instance.OnMovement;
                    @Movement.canceled += instance.OnMovement;
                    @Jump.started += instance.OnJump;
                    @Jump.performed += instance.OnJump;
                    @Jump.canceled += instance.OnJump;
                    @Look.started += instance.OnLook;
                    @Look.performed += instance.OnLook;
                    @Look.canceled += instance.OnLook;
                    @Crouch.started += instance.OnCrouch;
                    @Crouch.performed += instance.OnCrouch;
                    @Crouch.canceled += instance.OnCrouch;
                }
            }
        }
        public GameplayActions @Gameplay => new GameplayActions(this);

        // HandLeft
        private readonly InputActionMap m_HandLeft;
        private IHandLeftActions m_HandLeftActionsCallbackInterface;
        private readonly InputAction m_HandLeft_GripAxis;
        private readonly InputAction m_HandLeft_SecondaryButton;
        public struct HandLeftActions
        {
            private @DesktopInputActions m_Wrapper;
            public HandLeftActions(@DesktopInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @GripAxis => m_Wrapper.m_HandLeft_GripAxis;
            public InputAction @SecondaryButton => m_Wrapper.m_HandLeft_SecondaryButton;
            public InputActionMap Get() { return m_Wrapper.m_HandLeft; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(HandLeftActions set) { return set.Get(); }
            public void SetCallbacks(IHandLeftActions instance)
            {
                if (m_Wrapper.m_HandLeftActionsCallbackInterface != null)
                {
                    @GripAxis.started -= m_Wrapper.m_HandLeftActionsCallbackInterface.OnGripAxis;
                    @GripAxis.performed -= m_Wrapper.m_HandLeftActionsCallbackInterface.OnGripAxis;
                    @GripAxis.canceled -= m_Wrapper.m_HandLeftActionsCallbackInterface.OnGripAxis;
                    @SecondaryButton.started -= m_Wrapper.m_HandLeftActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.performed -= m_Wrapper.m_HandLeftActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.canceled -= m_Wrapper.m_HandLeftActionsCallbackInterface.OnSecondaryButton;
                }
                m_Wrapper.m_HandLeftActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @GripAxis.started += instance.OnGripAxis;
                    @GripAxis.performed += instance.OnGripAxis;
                    @GripAxis.canceled += instance.OnGripAxis;
                    @SecondaryButton.started += instance.OnSecondaryButton;
                    @SecondaryButton.performed += instance.OnSecondaryButton;
                    @SecondaryButton.canceled += instance.OnSecondaryButton;
                }
            }
        }
        public HandLeftActions @HandLeft => new HandLeftActions(this);

        // HandRight
        private readonly InputActionMap m_HandRight;
        private IHandRightActions m_HandRightActionsCallbackInterface;
        private readonly InputAction m_HandRight_GripAxis;
        private readonly InputAction m_HandRight_ThumbstickAxis;
        private readonly InputAction m_HandRight_SecondaryButton;
        private readonly InputAction m_HandRight_TriggerAxis;
        public struct HandRightActions
        {
            private @DesktopInputActions m_Wrapper;
            public HandRightActions(@DesktopInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @GripAxis => m_Wrapper.m_HandRight_GripAxis;
            public InputAction @ThumbstickAxis => m_Wrapper.m_HandRight_ThumbstickAxis;
            public InputAction @SecondaryButton => m_Wrapper.m_HandRight_SecondaryButton;
            public InputAction @TriggerAxis => m_Wrapper.m_HandRight_TriggerAxis;
            public InputActionMap Get() { return m_Wrapper.m_HandRight; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(HandRightActions set) { return set.Get(); }
            public void SetCallbacks(IHandRightActions instance)
            {
                if (m_Wrapper.m_HandRightActionsCallbackInterface != null)
                {
                    @GripAxis.started -= m_Wrapper.m_HandRightActionsCallbackInterface.OnGripAxis;
                    @GripAxis.performed -= m_Wrapper.m_HandRightActionsCallbackInterface.OnGripAxis;
                    @GripAxis.canceled -= m_Wrapper.m_HandRightActionsCallbackInterface.OnGripAxis;
                    @ThumbstickAxis.started -= m_Wrapper.m_HandRightActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickAxis.performed -= m_Wrapper.m_HandRightActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickAxis.canceled -= m_Wrapper.m_HandRightActionsCallbackInterface.OnThumbstickAxis;
                    @SecondaryButton.started -= m_Wrapper.m_HandRightActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.performed -= m_Wrapper.m_HandRightActionsCallbackInterface.OnSecondaryButton;
                    @SecondaryButton.canceled -= m_Wrapper.m_HandRightActionsCallbackInterface.OnSecondaryButton;
                    @TriggerAxis.started -= m_Wrapper.m_HandRightActionsCallbackInterface.OnTriggerAxis;
                    @TriggerAxis.performed -= m_Wrapper.m_HandRightActionsCallbackInterface.OnTriggerAxis;
                    @TriggerAxis.canceled -= m_Wrapper.m_HandRightActionsCallbackInterface.OnTriggerAxis;
                }
                m_Wrapper.m_HandRightActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @GripAxis.started += instance.OnGripAxis;
                    @GripAxis.performed += instance.OnGripAxis;
                    @GripAxis.canceled += instance.OnGripAxis;
                    @ThumbstickAxis.started += instance.OnThumbstickAxis;
                    @ThumbstickAxis.performed += instance.OnThumbstickAxis;
                    @ThumbstickAxis.canceled += instance.OnThumbstickAxis;
                    @SecondaryButton.started += instance.OnSecondaryButton;
                    @SecondaryButton.performed += instance.OnSecondaryButton;
                    @SecondaryButton.canceled += instance.OnSecondaryButton;
                    @TriggerAxis.started += instance.OnTriggerAxis;
                    @TriggerAxis.performed += instance.OnTriggerAxis;
                    @TriggerAxis.canceled += instance.OnTriggerAxis;
                }
            }
        }
        public HandRightActions @HandRight => new HandRightActions(this);
        public interface IGameplayActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnJump(InputAction.CallbackContext context);
            void OnLook(InputAction.CallbackContext context);
            void OnCrouch(InputAction.CallbackContext context);
        }
        public interface IHandLeftActions
        {
            void OnGripAxis(InputAction.CallbackContext context);
            void OnSecondaryButton(InputAction.CallbackContext context);
        }
        public interface IHandRightActions
        {
            void OnGripAxis(InputAction.CallbackContext context);
            void OnThumbstickAxis(InputAction.CallbackContext context);
            void OnSecondaryButton(InputAction.CallbackContext context);
            void OnTriggerAxis(InputAction.CallbackContext context);
        }
    }
}
