//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Package/VAT.Input/Runtime/XR/XRInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace VAT.Input.XR
{
    public partial class @XRInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @XRInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""XRInputActions"",
    ""maps"": [
        {
            ""name"": ""XRControllerLeft"",
            ""id"": ""1845880b-d8cb-43a4-b423-8bcf0fa151a9"",
            ""actions"": [
                {
                    ""name"": ""Grip"",
                    ""type"": ""Value"",
                    ""id"": ""7d155261-99aa-454f-87bb-638957af4a69"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GripPressed"",
                    ""type"": ""Button"",
                    ""id"": ""02bee57e-1a86-4be5-98d6-6fe3a723aff4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""7b90c2d6-7d51-4101-83bd-977644a81be4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""e4271f5e-8dbc-4683-9329-b9acda76657b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""d9d96fda-7e43-4dc2-899b-e0388993d463"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerPressed"",
                    ""type"": ""Button"",
                    ""id"": ""b229add7-151a-4c68-83e9-d96c86284a03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbstickAxis"",
                    ""type"": ""Value"",
                    ""id"": ""0ceaa9c0-3e05-442b-bcad-bf77ffc8f62a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TrackpadAxis"",
                    ""type"": ""Value"",
                    ""id"": ""5db0d854-8b1e-4e5e-ab8c-94cfb5703a54"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThumbstickPressed"",
                    ""type"": ""Button"",
                    ""id"": ""05c82ffc-ab13-4428-b506-6801b2b36dc9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackpadPressed"",
                    ""type"": ""Button"",
                    ""id"": ""d7faa8b1-e409-404e-ab88-26e051934266"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""852ea393-23e7-4295-820d-693f9e239949"",
                    ""path"": ""<XRController>{LeftHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5094a28c-5290-41fb-92a0-40f494fbb66f"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cf8f441-b3af-4bf9-a459-0dc8e15020eb"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4edf3b3-d19b-4f2a-b37e-e44715154b5f"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca8b9e0f-7272-4d18-9251-71087fd0c6e3"",
                    ""path"": ""<XRController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd54510d-bf4f-4d65-8c94-681d31b43dd6"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65d1d3bb-7eee-446e-8ff5-4a9d63e2a5fd"",
                    ""path"": ""<XRController>{LeftHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b876e025-0dde-4d42-9311-0f3941bc6959"",
                    ""path"": ""<XRController>{LeftHand}/trackpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackpadAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6409e164-2388-419c-97dd-0fce2bfa7531"",
                    ""path"": ""<XRController>/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da9462cf-e9b3-4524-8473-25546a1a5bae"",
                    ""path"": ""<XRController>{LeftHand}/trackpadPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackpadPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""XRControllerRight"",
            ""id"": ""301fff59-e40e-4f3e-bcd2-b22364bee7b3"",
            ""actions"": [
                {
                    ""name"": ""Grip"",
                    ""type"": ""Value"",
                    ""id"": ""24936600-fd21-49f0-aa00-0f3000612c98"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GripPressed"",
                    ""type"": ""Button"",
                    ""id"": ""0de5b1b2-5760-42d7-8294-c83daa1747a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""57ca0fa6-6ac9-4e8d-8b83-1aacb1baa3ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""f241dbac-cf46-4fae-b3be-0246694e8980"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""a56fbe5a-a613-4739-a7de-959552a265ea"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerPressed"",
                    ""type"": ""Button"",
                    ""id"": ""1fb99bb3-cead-4e64-8ef2-07a676d970b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbstickAxis"",
                    ""type"": ""Value"",
                    ""id"": ""4842b991-3db1-4f6c-a782-884162fd5f6c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TrackpadAxis"",
                    ""type"": ""Value"",
                    ""id"": ""472057a6-6bc7-44d1-a7d4-c949407346c9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TrackpadPressed"",
                    ""type"": ""Button"",
                    ""id"": ""c54df489-96b2-40f6-8347-1829c57a3773"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbstickPressed"",
                    ""type"": ""Button"",
                    ""id"": ""610ec8b7-458f-4c82-8a7e-1786c0a868ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e9e4c509-28fe-4887-a6d7-5f0bdfab3407"",
                    ""path"": ""<XRController>{RightHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8474352-610a-40b3-a73c-5a65c3781d51"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f87d947-4782-4bd7-baa2-3b31b2c827f2"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd7b8ce1-10fa-470f-85c5-a4f43e1936e5"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8453af64-844e-4457-9966-5d668dc123f8"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f72a67a-9f44-4133-90ac-46ca3bb4621b"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee4cad0b-8a49-48aa-a05b-0b5a7ca01e3a"",
                    ""path"": ""<XRController>{RightHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cebb1303-b038-4477-92d7-cfa4cb27f4e5"",
                    ""path"": ""<XRController>{RightHand}/trackpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackpadAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""980370d9-9536-4fe0-a80f-ec4dfce84bc2"",
                    ""path"": ""<XRController>{RightHand}/trackpadPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackpadPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef1af6d9-f7e9-45a2-94b9-26ad088491aa"",
                    ""path"": ""<XRController>/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // XRControllerLeft
            m_XRControllerLeft = asset.FindActionMap("XRControllerLeft", throwIfNotFound: true);
            m_XRControllerLeft_Grip = m_XRControllerLeft.FindAction("Grip", throwIfNotFound: true);
            m_XRControllerLeft_GripPressed = m_XRControllerLeft.FindAction("GripPressed", throwIfNotFound: true);
            m_XRControllerLeft_PrimaryAction = m_XRControllerLeft.FindAction("PrimaryAction", throwIfNotFound: true);
            m_XRControllerLeft_SecondaryAction = m_XRControllerLeft.FindAction("SecondaryAction", throwIfNotFound: true);
            m_XRControllerLeft_Trigger = m_XRControllerLeft.FindAction("Trigger", throwIfNotFound: true);
            m_XRControllerLeft_TriggerPressed = m_XRControllerLeft.FindAction("TriggerPressed", throwIfNotFound: true);
            m_XRControllerLeft_ThumbstickAxis = m_XRControllerLeft.FindAction("ThumbstickAxis", throwIfNotFound: true);
            m_XRControllerLeft_TrackpadAxis = m_XRControllerLeft.FindAction("TrackpadAxis", throwIfNotFound: true);
            m_XRControllerLeft_ThumbstickPressed = m_XRControllerLeft.FindAction("ThumbstickPressed", throwIfNotFound: true);
            m_XRControllerLeft_TrackpadPressed = m_XRControllerLeft.FindAction("TrackpadPressed", throwIfNotFound: true);
            // XRControllerRight
            m_XRControllerRight = asset.FindActionMap("XRControllerRight", throwIfNotFound: true);
            m_XRControllerRight_Grip = m_XRControllerRight.FindAction("Grip", throwIfNotFound: true);
            m_XRControllerRight_GripPressed = m_XRControllerRight.FindAction("GripPressed", throwIfNotFound: true);
            m_XRControllerRight_PrimaryAction = m_XRControllerRight.FindAction("PrimaryAction", throwIfNotFound: true);
            m_XRControllerRight_SecondaryAction = m_XRControllerRight.FindAction("SecondaryAction", throwIfNotFound: true);
            m_XRControllerRight_Trigger = m_XRControllerRight.FindAction("Trigger", throwIfNotFound: true);
            m_XRControllerRight_TriggerPressed = m_XRControllerRight.FindAction("TriggerPressed", throwIfNotFound: true);
            m_XRControllerRight_ThumbstickAxis = m_XRControllerRight.FindAction("ThumbstickAxis", throwIfNotFound: true);
            m_XRControllerRight_TrackpadAxis = m_XRControllerRight.FindAction("TrackpadAxis", throwIfNotFound: true);
            m_XRControllerRight_TrackpadPressed = m_XRControllerRight.FindAction("TrackpadPressed", throwIfNotFound: true);
            m_XRControllerRight_ThumbstickPressed = m_XRControllerRight.FindAction("ThumbstickPressed", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // XRControllerLeft
        private readonly InputActionMap m_XRControllerLeft;
        private IXRControllerLeftActions m_XRControllerLeftActionsCallbackInterface;
        private readonly InputAction m_XRControllerLeft_Grip;
        private readonly InputAction m_XRControllerLeft_GripPressed;
        private readonly InputAction m_XRControllerLeft_PrimaryAction;
        private readonly InputAction m_XRControllerLeft_SecondaryAction;
        private readonly InputAction m_XRControllerLeft_Trigger;
        private readonly InputAction m_XRControllerLeft_TriggerPressed;
        private readonly InputAction m_XRControllerLeft_ThumbstickAxis;
        private readonly InputAction m_XRControllerLeft_TrackpadAxis;
        private readonly InputAction m_XRControllerLeft_ThumbstickPressed;
        private readonly InputAction m_XRControllerLeft_TrackpadPressed;
        public struct XRControllerLeftActions
        {
            private @XRInputActions m_Wrapper;
            public XRControllerLeftActions(@XRInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Grip => m_Wrapper.m_XRControllerLeft_Grip;
            public InputAction @GripPressed => m_Wrapper.m_XRControllerLeft_GripPressed;
            public InputAction @PrimaryAction => m_Wrapper.m_XRControllerLeft_PrimaryAction;
            public InputAction @SecondaryAction => m_Wrapper.m_XRControllerLeft_SecondaryAction;
            public InputAction @Trigger => m_Wrapper.m_XRControllerLeft_Trigger;
            public InputAction @TriggerPressed => m_Wrapper.m_XRControllerLeft_TriggerPressed;
            public InputAction @ThumbstickAxis => m_Wrapper.m_XRControllerLeft_ThumbstickAxis;
            public InputAction @TrackpadAxis => m_Wrapper.m_XRControllerLeft_TrackpadAxis;
            public InputAction @ThumbstickPressed => m_Wrapper.m_XRControllerLeft_ThumbstickPressed;
            public InputAction @TrackpadPressed => m_Wrapper.m_XRControllerLeft_TrackpadPressed;
            public InputActionMap Get() { return m_Wrapper.m_XRControllerLeft; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(XRControllerLeftActions set) { return set.Get(); }
            public void SetCallbacks(IXRControllerLeftActions instance)
            {
                if (m_Wrapper.m_XRControllerLeftActionsCallbackInterface != null)
                {
                    @Grip.started -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnGrip;
                    @Grip.performed -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnGrip;
                    @Grip.canceled -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnGrip;
                    @GripPressed.started -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnGripPressed;
                    @GripPressed.performed -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnGripPressed;
                    @GripPressed.canceled -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnGripPressed;
                    @PrimaryAction.started -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnPrimaryAction;
                    @PrimaryAction.performed -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnPrimaryAction;
                    @PrimaryAction.canceled -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnPrimaryAction;
                    @SecondaryAction.started -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnSecondaryAction;
                    @SecondaryAction.performed -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnSecondaryAction;
                    @SecondaryAction.canceled -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnSecondaryAction;
                    @Trigger.started -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTrigger;
                    @Trigger.performed -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTrigger;
                    @Trigger.canceled -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTrigger;
                    @TriggerPressed.started -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTriggerPressed;
                    @TriggerPressed.performed -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTriggerPressed;
                    @TriggerPressed.canceled -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTriggerPressed;
                    @ThumbstickAxis.started -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickAxis.performed -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickAxis.canceled -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnThumbstickAxis;
                    @TrackpadAxis.started -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTrackpadAxis;
                    @TrackpadAxis.performed -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTrackpadAxis;
                    @TrackpadAxis.canceled -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTrackpadAxis;
                    @ThumbstickPressed.started -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnThumbstickPressed;
                    @ThumbstickPressed.performed -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnThumbstickPressed;
                    @ThumbstickPressed.canceled -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnThumbstickPressed;
                    @TrackpadPressed.started -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTrackpadPressed;
                    @TrackpadPressed.performed -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTrackpadPressed;
                    @TrackpadPressed.canceled -= m_Wrapper.m_XRControllerLeftActionsCallbackInterface.OnTrackpadPressed;
                }
                m_Wrapper.m_XRControllerLeftActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Grip.started += instance.OnGrip;
                    @Grip.performed += instance.OnGrip;
                    @Grip.canceled += instance.OnGrip;
                    @GripPressed.started += instance.OnGripPressed;
                    @GripPressed.performed += instance.OnGripPressed;
                    @GripPressed.canceled += instance.OnGripPressed;
                    @PrimaryAction.started += instance.OnPrimaryAction;
                    @PrimaryAction.performed += instance.OnPrimaryAction;
                    @PrimaryAction.canceled += instance.OnPrimaryAction;
                    @SecondaryAction.started += instance.OnSecondaryAction;
                    @SecondaryAction.performed += instance.OnSecondaryAction;
                    @SecondaryAction.canceled += instance.OnSecondaryAction;
                    @Trigger.started += instance.OnTrigger;
                    @Trigger.performed += instance.OnTrigger;
                    @Trigger.canceled += instance.OnTrigger;
                    @TriggerPressed.started += instance.OnTriggerPressed;
                    @TriggerPressed.performed += instance.OnTriggerPressed;
                    @TriggerPressed.canceled += instance.OnTriggerPressed;
                    @ThumbstickAxis.started += instance.OnThumbstickAxis;
                    @ThumbstickAxis.performed += instance.OnThumbstickAxis;
                    @ThumbstickAxis.canceled += instance.OnThumbstickAxis;
                    @TrackpadAxis.started += instance.OnTrackpadAxis;
                    @TrackpadAxis.performed += instance.OnTrackpadAxis;
                    @TrackpadAxis.canceled += instance.OnTrackpadAxis;
                    @ThumbstickPressed.started += instance.OnThumbstickPressed;
                    @ThumbstickPressed.performed += instance.OnThumbstickPressed;
                    @ThumbstickPressed.canceled += instance.OnThumbstickPressed;
                    @TrackpadPressed.started += instance.OnTrackpadPressed;
                    @TrackpadPressed.performed += instance.OnTrackpadPressed;
                    @TrackpadPressed.canceled += instance.OnTrackpadPressed;
                }
            }
        }
        public XRControllerLeftActions @XRControllerLeft => new XRControllerLeftActions(this);

        // XRControllerRight
        private readonly InputActionMap m_XRControllerRight;
        private IXRControllerRightActions m_XRControllerRightActionsCallbackInterface;
        private readonly InputAction m_XRControllerRight_Grip;
        private readonly InputAction m_XRControllerRight_GripPressed;
        private readonly InputAction m_XRControllerRight_PrimaryAction;
        private readonly InputAction m_XRControllerRight_SecondaryAction;
        private readonly InputAction m_XRControllerRight_Trigger;
        private readonly InputAction m_XRControllerRight_TriggerPressed;
        private readonly InputAction m_XRControllerRight_ThumbstickAxis;
        private readonly InputAction m_XRControllerRight_TrackpadAxis;
        private readonly InputAction m_XRControllerRight_TrackpadPressed;
        private readonly InputAction m_XRControllerRight_ThumbstickPressed;
        public struct XRControllerRightActions
        {
            private @XRInputActions m_Wrapper;
            public XRControllerRightActions(@XRInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Grip => m_Wrapper.m_XRControllerRight_Grip;
            public InputAction @GripPressed => m_Wrapper.m_XRControllerRight_GripPressed;
            public InputAction @PrimaryAction => m_Wrapper.m_XRControllerRight_PrimaryAction;
            public InputAction @SecondaryAction => m_Wrapper.m_XRControllerRight_SecondaryAction;
            public InputAction @Trigger => m_Wrapper.m_XRControllerRight_Trigger;
            public InputAction @TriggerPressed => m_Wrapper.m_XRControllerRight_TriggerPressed;
            public InputAction @ThumbstickAxis => m_Wrapper.m_XRControllerRight_ThumbstickAxis;
            public InputAction @TrackpadAxis => m_Wrapper.m_XRControllerRight_TrackpadAxis;
            public InputAction @TrackpadPressed => m_Wrapper.m_XRControllerRight_TrackpadPressed;
            public InputAction @ThumbstickPressed => m_Wrapper.m_XRControllerRight_ThumbstickPressed;
            public InputActionMap Get() { return m_Wrapper.m_XRControllerRight; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(XRControllerRightActions set) { return set.Get(); }
            public void SetCallbacks(IXRControllerRightActions instance)
            {
                if (m_Wrapper.m_XRControllerRightActionsCallbackInterface != null)
                {
                    @Grip.started -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnGrip;
                    @Grip.performed -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnGrip;
                    @Grip.canceled -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnGrip;
                    @GripPressed.started -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnGripPressed;
                    @GripPressed.performed -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnGripPressed;
                    @GripPressed.canceled -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnGripPressed;
                    @PrimaryAction.started -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnPrimaryAction;
                    @PrimaryAction.performed -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnPrimaryAction;
                    @PrimaryAction.canceled -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnPrimaryAction;
                    @SecondaryAction.started -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnSecondaryAction;
                    @SecondaryAction.performed -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnSecondaryAction;
                    @SecondaryAction.canceled -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnSecondaryAction;
                    @Trigger.started -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTrigger;
                    @Trigger.performed -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTrigger;
                    @Trigger.canceled -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTrigger;
                    @TriggerPressed.started -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTriggerPressed;
                    @TriggerPressed.performed -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTriggerPressed;
                    @TriggerPressed.canceled -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTriggerPressed;
                    @ThumbstickAxis.started -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickAxis.performed -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickAxis.canceled -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnThumbstickAxis;
                    @TrackpadAxis.started -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTrackpadAxis;
                    @TrackpadAxis.performed -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTrackpadAxis;
                    @TrackpadAxis.canceled -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTrackpadAxis;
                    @TrackpadPressed.started -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTrackpadPressed;
                    @TrackpadPressed.performed -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTrackpadPressed;
                    @TrackpadPressed.canceled -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnTrackpadPressed;
                    @ThumbstickPressed.started -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnThumbstickPressed;
                    @ThumbstickPressed.performed -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnThumbstickPressed;
                    @ThumbstickPressed.canceled -= m_Wrapper.m_XRControllerRightActionsCallbackInterface.OnThumbstickPressed;
                }
                m_Wrapper.m_XRControllerRightActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Grip.started += instance.OnGrip;
                    @Grip.performed += instance.OnGrip;
                    @Grip.canceled += instance.OnGrip;
                    @GripPressed.started += instance.OnGripPressed;
                    @GripPressed.performed += instance.OnGripPressed;
                    @GripPressed.canceled += instance.OnGripPressed;
                    @PrimaryAction.started += instance.OnPrimaryAction;
                    @PrimaryAction.performed += instance.OnPrimaryAction;
                    @PrimaryAction.canceled += instance.OnPrimaryAction;
                    @SecondaryAction.started += instance.OnSecondaryAction;
                    @SecondaryAction.performed += instance.OnSecondaryAction;
                    @SecondaryAction.canceled += instance.OnSecondaryAction;
                    @Trigger.started += instance.OnTrigger;
                    @Trigger.performed += instance.OnTrigger;
                    @Trigger.canceled += instance.OnTrigger;
                    @TriggerPressed.started += instance.OnTriggerPressed;
                    @TriggerPressed.performed += instance.OnTriggerPressed;
                    @TriggerPressed.canceled += instance.OnTriggerPressed;
                    @ThumbstickAxis.started += instance.OnThumbstickAxis;
                    @ThumbstickAxis.performed += instance.OnThumbstickAxis;
                    @ThumbstickAxis.canceled += instance.OnThumbstickAxis;
                    @TrackpadAxis.started += instance.OnTrackpadAxis;
                    @TrackpadAxis.performed += instance.OnTrackpadAxis;
                    @TrackpadAxis.canceled += instance.OnTrackpadAxis;
                    @TrackpadPressed.started += instance.OnTrackpadPressed;
                    @TrackpadPressed.performed += instance.OnTrackpadPressed;
                    @TrackpadPressed.canceled += instance.OnTrackpadPressed;
                    @ThumbstickPressed.started += instance.OnThumbstickPressed;
                    @ThumbstickPressed.performed += instance.OnThumbstickPressed;
                    @ThumbstickPressed.canceled += instance.OnThumbstickPressed;
                }
            }
        }
        public XRControllerRightActions @XRControllerRight => new XRControllerRightActions(this);
        public interface IXRControllerLeftActions
        {
            void OnGrip(InputAction.CallbackContext context);
            void OnGripPressed(InputAction.CallbackContext context);
            void OnPrimaryAction(InputAction.CallbackContext context);
            void OnSecondaryAction(InputAction.CallbackContext context);
            void OnTrigger(InputAction.CallbackContext context);
            void OnTriggerPressed(InputAction.CallbackContext context);
            void OnThumbstickAxis(InputAction.CallbackContext context);
            void OnTrackpadAxis(InputAction.CallbackContext context);
            void OnThumbstickPressed(InputAction.CallbackContext context);
            void OnTrackpadPressed(InputAction.CallbackContext context);
        }
        public interface IXRControllerRightActions
        {
            void OnGrip(InputAction.CallbackContext context);
            void OnGripPressed(InputAction.CallbackContext context);
            void OnPrimaryAction(InputAction.CallbackContext context);
            void OnSecondaryAction(InputAction.CallbackContext context);
            void OnTrigger(InputAction.CallbackContext context);
            void OnTriggerPressed(InputAction.CallbackContext context);
            void OnThumbstickAxis(InputAction.CallbackContext context);
            void OnTrackpadAxis(InputAction.CallbackContext context);
            void OnTrackpadPressed(InputAction.CallbackContext context);
            void OnThumbstickPressed(InputAction.CallbackContext context);
        }
    }
}
