//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Package/VAT.Input/Runtime/XR/XRInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace VAT.Input.XR
{
    public partial class @XRInputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @XRInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""XRInputActions"",
    ""maps"": [
        {
            ""name"": ""HMD"",
            ""id"": ""973adddd-7e16-44f2-93f4-5b768c217105"",
            ""actions"": [
                {
                    ""name"": ""CenterEyePosition"",
                    ""type"": ""Value"",
                    ""id"": ""29ceceb5-cf27-4947-bf48-3e1d4065c996"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CenterEyeRotation"",
                    ""type"": ""Value"",
                    ""id"": ""14450f94-f7f8-4f24-874f-fff6d600f383"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c86d4df6-60fd-4672-82ef-605bea611bae"",
                    ""path"": ""<XRHMD>/centerEyePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CenterEyePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96fac988-8061-4159-81cd-2c4af003a337"",
                    ""path"": ""<XRHMD>/centerEyeRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CenterEyeRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ControllerLeft"",
            ""id"": ""e2fbc867-e8e5-4896-92f7-f19ed880cb49"",
            ""actions"": [
                {
                    ""name"": ""TriggerAxis"",
                    ""type"": ""Value"",
                    ""id"": ""21763553-9779-4c07-b99d-e836cd10badc"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerPressed"",
                    ""type"": ""Button"",
                    ""id"": ""8ffcab54-554d-4f10-8310-2c03b94fa221"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripAxis"",
                    ""type"": ""Value"",
                    ""id"": ""cfdc0736-0b61-4100-b704-f390c233b1a8"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GripPressed"",
                    ""type"": ""Button"",
                    ""id"": ""755ef796-6efe-485c-99d9-f939255e334a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripForce"",
                    ""type"": ""Value"",
                    ""id"": ""3694b4e8-dcf2-4e30-a490-3cddb8bab69c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""af3514c2-6c5b-48c6-a85c-a6a1f0ad29ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryButtonTouched"",
                    ""type"": ""Button"",
                    ""id"": ""f5e96c56-2625-4d14-ac7d-9f173cda2385"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""ea52817a-d3bc-4565-a849-f5492d81bd7c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryButtonTouched"",
                    ""type"": ""Button"",
                    ""id"": ""a0970f74-a388-4469-b8b3-723f3dac58b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbstickAxis"",
                    ""type"": ""Value"",
                    ""id"": ""7d81304b-c149-4c30-8e06-046e0b2ece41"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThumbstickPressed"",
                    ""type"": ""Button"",
                    ""id"": ""8ef1602d-ca53-40b5-9448-3ec63248bd03"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbstickTouched"",
                    ""type"": ""Button"",
                    ""id"": ""2ce38186-5ad6-434d-b8d5-256f02856c10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackpadAxis"",
                    ""type"": ""Value"",
                    ""id"": ""00e03b81-d415-4e00-b8c7-27d2b5738352"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TrackpadPressed"",
                    ""type"": ""Button"",
                    ""id"": ""e9728a16-1f90-42c2-8a6b-6da548186654"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackpadTouched"",
                    ""type"": ""Button"",
                    ""id"": ""01b86b72-1ec3-4225-868a-bceb64b7963d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f318b43f-fdf5-4335-9159-06499e3403c3"",
                    ""path"": ""<XRController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""63b998e9-1329-47fb-8e7d-ebeb62495838"",
                    ""path"": ""<XRController>{LeftHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8468245-785c-453a-ab5c-0126da09dcc1"",
                    ""path"": ""<XRController>{LeftHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4a67c07-a27b-42ad-a6be-4948ee311708"",
                    ""path"": ""<XRController>{LeftHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68e26aba-5002-476a-948b-348d11bc0260"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1adc7e94-56de-4714-927a-acf141e09ada"",
                    ""path"": ""<XRController>{LeftHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButtonTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1500a367-ac50-4774-8ff0-99519ea3584e"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b90a999-7b3b-4bfa-8387-bb273563bd92"",
                    ""path"": ""<XRController>{LeftHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButtonTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec6bb6e0-8fe6-414a-8109-4b4b2b9f0f46"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcdf37e0-5ed1-4d59-8e12-e39c4567f5c8"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1718b7c9-0cf1-4fbc-8fb9-dae68b080d31"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0115bc48-63b2-4e9b-9eb0-496bc05c31ef"",
                    ""path"": ""<ValveIndexController>{LeftHand}/gripForce"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripForce"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab95bff9-1fda-473f-815c-82e62cf30a43"",
                    ""path"": ""<OculusTouchController>{LeftHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripForce"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4eb96f56-add1-4727-81f1-d16bcd17f985"",
                    ""path"": ""<XRController>{LeftHand}/trackpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackpadAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d7e92ad-1739-4be6-8179-17e7cedca87d"",
                    ""path"": ""<XRController>{LeftHand}/trackpadPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackpadPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""454e25e6-04ee-4d8a-abfa-18788d037b37"",
                    ""path"": ""<XRController>{LeftHand}/trackpadTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackpadTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ControllerRight"",
            ""id"": ""a9684dce-4475-4dea-97e1-7607ebdc2c4e"",
            ""actions"": [
                {
                    ""name"": ""TriggerAxis"",
                    ""type"": ""Value"",
                    ""id"": ""d9378094-ea78-43cb-81e7-820db6bff3d7"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerPressed"",
                    ""type"": ""Button"",
                    ""id"": ""8383f4be-cb4c-464a-aebf-934bb4ab8ef5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripAxis"",
                    ""type"": ""Value"",
                    ""id"": ""e84a147d-1812-4e8b-88bc-5577e60deff8"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GripPressed"",
                    ""type"": ""Button"",
                    ""id"": ""4a65766f-65b1-42d4-9529-3300f4760b3c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripForce"",
                    ""type"": ""Value"",
                    ""id"": ""9cb564e1-a152-4cb6-a36d-e6156dd644fa"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""1c6d3cf6-c62c-447e-9547-fc9fb67e666a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryButtonTouched"",
                    ""type"": ""Button"",
                    ""id"": ""ed7b06db-5141-4df1-b731-4158449ed369"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""041e1b29-4e82-46c0-8f21-6546069d8f3e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryButtonTouched"",
                    ""type"": ""Button"",
                    ""id"": ""e2ff70d6-4b96-43f8-85a6-98a6d64d2c92"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbstickAxis"",
                    ""type"": ""Value"",
                    ""id"": ""2813fefd-cf83-4d7e-ae87-6186711a5226"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThumbstickPressed"",
                    ""type"": ""Button"",
                    ""id"": ""af1d06df-b705-4366-90b6-f2840d0ea9be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThumbstickTouched"",
                    ""type"": ""Button"",
                    ""id"": ""0fa33267-6700-43ad-b7ac-a1de5f03b158"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackpadAxis"",
                    ""type"": ""Value"",
                    ""id"": ""2c6d69bf-148f-4f90-9193-45f7754e68bd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TrackpadPressed"",
                    ""type"": ""Button"",
                    ""id"": ""e5066554-2724-402a-8cc8-618174faa4f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrackpadTouched"",
                    ""type"": ""Button"",
                    ""id"": ""59b94e5d-83f1-41ad-9bb5-695f2e9203c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f9f7e95b-5644-4ba9-96fd-907c79973ee2"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4a0912d-bbe5-4dbf-93db-338903c3e6f9"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e48d9ba4-1852-4c7a-938d-6e04768c911e"",
                    ""path"": ""<XRController>{RightHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f227b527-400c-47dd-b69c-abf6f9a3ca7e"",
                    ""path"": ""<XRController>{RightHand}/gripPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5eb32936-9b30-444b-9cd1-19887376305e"",
                    ""path"": ""<ValveIndexController>{RightHand}/gripForce"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripForce"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c5e54b3-4f0e-4669-a1a4-4e228ec0b162"",
                    ""path"": ""<OculusTouchController>{RightHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripForce"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88e2f87c-5759-491b-8061-f9fc06c39ee4"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f3a2bf5-db19-4819-a5ca-425a979b3963"",
                    ""path"": ""<XRController>{RightHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButtonTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3482be10-7a1a-45b3-b599-ddd86d7d3e2d"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc24c4d4-76f9-460b-b41e-69efb15cde94"",
                    ""path"": ""<XRController>{RightHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryButtonTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed507f1b-51e0-4d45-898c-9818df23d8e9"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45a25cb4-1aab-4ef4-a246-60b146e914b7"",
                    ""path"": ""<XRController>{RightHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47714e79-c98e-41f9-a4ca-f5b0aba3516b"",
                    ""path"": ""<XRController>{RightHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThumbstickTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bc349b3-46fa-45dc-843c-39608a54d571"",
                    ""path"": ""<XRController>{RightHand}/trackpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackpadAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ced1a33-53e0-4720-bcc1-9274d14d6165"",
                    ""path"": ""<XRController>{RightHand}/trackpadPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackpadPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2aa92fee-a199-405c-92bb-d576254eec3f"",
                    ""path"": ""<XRController>{RightHand}/trackpadTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrackpadTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // HMD
            m_HMD = asset.FindActionMap("HMD", throwIfNotFound: true);
            m_HMD_CenterEyePosition = m_HMD.FindAction("CenterEyePosition", throwIfNotFound: true);
            m_HMD_CenterEyeRotation = m_HMD.FindAction("CenterEyeRotation", throwIfNotFound: true);
            // ControllerLeft
            m_ControllerLeft = asset.FindActionMap("ControllerLeft", throwIfNotFound: true);
            m_ControllerLeft_TriggerAxis = m_ControllerLeft.FindAction("TriggerAxis", throwIfNotFound: true);
            m_ControllerLeft_TriggerPressed = m_ControllerLeft.FindAction("TriggerPressed", throwIfNotFound: true);
            m_ControllerLeft_GripAxis = m_ControllerLeft.FindAction("GripAxis", throwIfNotFound: true);
            m_ControllerLeft_GripPressed = m_ControllerLeft.FindAction("GripPressed", throwIfNotFound: true);
            m_ControllerLeft_GripForce = m_ControllerLeft.FindAction("GripForce", throwIfNotFound: true);
            m_ControllerLeft_PrimaryButtonPressed = m_ControllerLeft.FindAction("PrimaryButtonPressed", throwIfNotFound: true);
            m_ControllerLeft_PrimaryButtonTouched = m_ControllerLeft.FindAction("PrimaryButtonTouched", throwIfNotFound: true);
            m_ControllerLeft_SecondaryButtonPressed = m_ControllerLeft.FindAction("SecondaryButtonPressed", throwIfNotFound: true);
            m_ControllerLeft_SecondaryButtonTouched = m_ControllerLeft.FindAction("SecondaryButtonTouched", throwIfNotFound: true);
            m_ControllerLeft_ThumbstickAxis = m_ControllerLeft.FindAction("ThumbstickAxis", throwIfNotFound: true);
            m_ControllerLeft_ThumbstickPressed = m_ControllerLeft.FindAction("ThumbstickPressed", throwIfNotFound: true);
            m_ControllerLeft_ThumbstickTouched = m_ControllerLeft.FindAction("ThumbstickTouched", throwIfNotFound: true);
            m_ControllerLeft_TrackpadAxis = m_ControllerLeft.FindAction("TrackpadAxis", throwIfNotFound: true);
            m_ControllerLeft_TrackpadPressed = m_ControllerLeft.FindAction("TrackpadPressed", throwIfNotFound: true);
            m_ControllerLeft_TrackpadTouched = m_ControllerLeft.FindAction("TrackpadTouched", throwIfNotFound: true);
            // ControllerRight
            m_ControllerRight = asset.FindActionMap("ControllerRight", throwIfNotFound: true);
            m_ControllerRight_TriggerAxis = m_ControllerRight.FindAction("TriggerAxis", throwIfNotFound: true);
            m_ControllerRight_TriggerPressed = m_ControllerRight.FindAction("TriggerPressed", throwIfNotFound: true);
            m_ControllerRight_GripAxis = m_ControllerRight.FindAction("GripAxis", throwIfNotFound: true);
            m_ControllerRight_GripPressed = m_ControllerRight.FindAction("GripPressed", throwIfNotFound: true);
            m_ControllerRight_GripForce = m_ControllerRight.FindAction("GripForce", throwIfNotFound: true);
            m_ControllerRight_PrimaryButtonPressed = m_ControllerRight.FindAction("PrimaryButtonPressed", throwIfNotFound: true);
            m_ControllerRight_PrimaryButtonTouched = m_ControllerRight.FindAction("PrimaryButtonTouched", throwIfNotFound: true);
            m_ControllerRight_SecondaryButtonPressed = m_ControllerRight.FindAction("SecondaryButtonPressed", throwIfNotFound: true);
            m_ControllerRight_SecondaryButtonTouched = m_ControllerRight.FindAction("SecondaryButtonTouched", throwIfNotFound: true);
            m_ControllerRight_ThumbstickAxis = m_ControllerRight.FindAction("ThumbstickAxis", throwIfNotFound: true);
            m_ControllerRight_ThumbstickPressed = m_ControllerRight.FindAction("ThumbstickPressed", throwIfNotFound: true);
            m_ControllerRight_ThumbstickTouched = m_ControllerRight.FindAction("ThumbstickTouched", throwIfNotFound: true);
            m_ControllerRight_TrackpadAxis = m_ControllerRight.FindAction("TrackpadAxis", throwIfNotFound: true);
            m_ControllerRight_TrackpadPressed = m_ControllerRight.FindAction("TrackpadPressed", throwIfNotFound: true);
            m_ControllerRight_TrackpadTouched = m_ControllerRight.FindAction("TrackpadTouched", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // HMD
        private readonly InputActionMap m_HMD;
        private IHMDActions m_HMDActionsCallbackInterface;
        private readonly InputAction m_HMD_CenterEyePosition;
        private readonly InputAction m_HMD_CenterEyeRotation;
        public struct HMDActions
        {
            private @XRInputActions m_Wrapper;
            public HMDActions(@XRInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @CenterEyePosition => m_Wrapper.m_HMD_CenterEyePosition;
            public InputAction @CenterEyeRotation => m_Wrapper.m_HMD_CenterEyeRotation;
            public InputActionMap Get() { return m_Wrapper.m_HMD; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(HMDActions set) { return set.Get(); }
            public void SetCallbacks(IHMDActions instance)
            {
                if (m_Wrapper.m_HMDActionsCallbackInterface != null)
                {
                    @CenterEyePosition.started -= m_Wrapper.m_HMDActionsCallbackInterface.OnCenterEyePosition;
                    @CenterEyePosition.performed -= m_Wrapper.m_HMDActionsCallbackInterface.OnCenterEyePosition;
                    @CenterEyePosition.canceled -= m_Wrapper.m_HMDActionsCallbackInterface.OnCenterEyePosition;
                    @CenterEyeRotation.started -= m_Wrapper.m_HMDActionsCallbackInterface.OnCenterEyeRotation;
                    @CenterEyeRotation.performed -= m_Wrapper.m_HMDActionsCallbackInterface.OnCenterEyeRotation;
                    @CenterEyeRotation.canceled -= m_Wrapper.m_HMDActionsCallbackInterface.OnCenterEyeRotation;
                }
                m_Wrapper.m_HMDActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @CenterEyePosition.started += instance.OnCenterEyePosition;
                    @CenterEyePosition.performed += instance.OnCenterEyePosition;
                    @CenterEyePosition.canceled += instance.OnCenterEyePosition;
                    @CenterEyeRotation.started += instance.OnCenterEyeRotation;
                    @CenterEyeRotation.performed += instance.OnCenterEyeRotation;
                    @CenterEyeRotation.canceled += instance.OnCenterEyeRotation;
                }
            }
        }
        public HMDActions @HMD => new HMDActions(this);

        // ControllerLeft
        private readonly InputActionMap m_ControllerLeft;
        private IControllerLeftActions m_ControllerLeftActionsCallbackInterface;
        private readonly InputAction m_ControllerLeft_TriggerAxis;
        private readonly InputAction m_ControllerLeft_TriggerPressed;
        private readonly InputAction m_ControllerLeft_GripAxis;
        private readonly InputAction m_ControllerLeft_GripPressed;
        private readonly InputAction m_ControllerLeft_GripForce;
        private readonly InputAction m_ControllerLeft_PrimaryButtonPressed;
        private readonly InputAction m_ControllerLeft_PrimaryButtonTouched;
        private readonly InputAction m_ControllerLeft_SecondaryButtonPressed;
        private readonly InputAction m_ControllerLeft_SecondaryButtonTouched;
        private readonly InputAction m_ControllerLeft_ThumbstickAxis;
        private readonly InputAction m_ControllerLeft_ThumbstickPressed;
        private readonly InputAction m_ControllerLeft_ThumbstickTouched;
        private readonly InputAction m_ControllerLeft_TrackpadAxis;
        private readonly InputAction m_ControllerLeft_TrackpadPressed;
        private readonly InputAction m_ControllerLeft_TrackpadTouched;
        public struct ControllerLeftActions
        {
            private @XRInputActions m_Wrapper;
            public ControllerLeftActions(@XRInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @TriggerAxis => m_Wrapper.m_ControllerLeft_TriggerAxis;
            public InputAction @TriggerPressed => m_Wrapper.m_ControllerLeft_TriggerPressed;
            public InputAction @GripAxis => m_Wrapper.m_ControllerLeft_GripAxis;
            public InputAction @GripPressed => m_Wrapper.m_ControllerLeft_GripPressed;
            public InputAction @GripForce => m_Wrapper.m_ControllerLeft_GripForce;
            public InputAction @PrimaryButtonPressed => m_Wrapper.m_ControllerLeft_PrimaryButtonPressed;
            public InputAction @PrimaryButtonTouched => m_Wrapper.m_ControllerLeft_PrimaryButtonTouched;
            public InputAction @SecondaryButtonPressed => m_Wrapper.m_ControllerLeft_SecondaryButtonPressed;
            public InputAction @SecondaryButtonTouched => m_Wrapper.m_ControllerLeft_SecondaryButtonTouched;
            public InputAction @ThumbstickAxis => m_Wrapper.m_ControllerLeft_ThumbstickAxis;
            public InputAction @ThumbstickPressed => m_Wrapper.m_ControllerLeft_ThumbstickPressed;
            public InputAction @ThumbstickTouched => m_Wrapper.m_ControllerLeft_ThumbstickTouched;
            public InputAction @TrackpadAxis => m_Wrapper.m_ControllerLeft_TrackpadAxis;
            public InputAction @TrackpadPressed => m_Wrapper.m_ControllerLeft_TrackpadPressed;
            public InputAction @TrackpadTouched => m_Wrapper.m_ControllerLeft_TrackpadTouched;
            public InputActionMap Get() { return m_Wrapper.m_ControllerLeft; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(ControllerLeftActions set) { return set.Get(); }
            public void SetCallbacks(IControllerLeftActions instance)
            {
                if (m_Wrapper.m_ControllerLeftActionsCallbackInterface != null)
                {
                    @TriggerAxis.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTriggerAxis;
                    @TriggerAxis.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTriggerAxis;
                    @TriggerAxis.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTriggerAxis;
                    @TriggerPressed.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTriggerPressed;
                    @TriggerPressed.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTriggerPressed;
                    @TriggerPressed.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTriggerPressed;
                    @GripAxis.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnGripAxis;
                    @GripAxis.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnGripAxis;
                    @GripAxis.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnGripAxis;
                    @GripPressed.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnGripPressed;
                    @GripPressed.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnGripPressed;
                    @GripPressed.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnGripPressed;
                    @GripForce.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnGripForce;
                    @GripForce.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnGripForce;
                    @GripForce.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnGripForce;
                    @PrimaryButtonPressed.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnPrimaryButtonPressed;
                    @PrimaryButtonPressed.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnPrimaryButtonPressed;
                    @PrimaryButtonPressed.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnPrimaryButtonPressed;
                    @PrimaryButtonTouched.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnPrimaryButtonTouched;
                    @SecondaryButtonPressed.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnSecondaryButtonPressed;
                    @SecondaryButtonPressed.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnSecondaryButtonPressed;
                    @SecondaryButtonPressed.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnSecondaryButtonPressed;
                    @SecondaryButtonTouched.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnSecondaryButtonTouched;
                    @ThumbstickAxis.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickAxis.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickAxis.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickPressed.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnThumbstickPressed;
                    @ThumbstickPressed.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnThumbstickPressed;
                    @ThumbstickPressed.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnThumbstickPressed;
                    @ThumbstickTouched.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnThumbstickTouched;
                    @ThumbstickTouched.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnThumbstickTouched;
                    @ThumbstickTouched.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnThumbstickTouched;
                    @TrackpadAxis.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTrackpadAxis;
                    @TrackpadAxis.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTrackpadAxis;
                    @TrackpadAxis.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTrackpadAxis;
                    @TrackpadPressed.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTrackpadPressed;
                    @TrackpadPressed.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTrackpadPressed;
                    @TrackpadPressed.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTrackpadPressed;
                    @TrackpadTouched.started -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTrackpadTouched;
                    @TrackpadTouched.performed -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTrackpadTouched;
                    @TrackpadTouched.canceled -= m_Wrapper.m_ControllerLeftActionsCallbackInterface.OnTrackpadTouched;
                }
                m_Wrapper.m_ControllerLeftActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @TriggerAxis.started += instance.OnTriggerAxis;
                    @TriggerAxis.performed += instance.OnTriggerAxis;
                    @TriggerAxis.canceled += instance.OnTriggerAxis;
                    @TriggerPressed.started += instance.OnTriggerPressed;
                    @TriggerPressed.performed += instance.OnTriggerPressed;
                    @TriggerPressed.canceled += instance.OnTriggerPressed;
                    @GripAxis.started += instance.OnGripAxis;
                    @GripAxis.performed += instance.OnGripAxis;
                    @GripAxis.canceled += instance.OnGripAxis;
                    @GripPressed.started += instance.OnGripPressed;
                    @GripPressed.performed += instance.OnGripPressed;
                    @GripPressed.canceled += instance.OnGripPressed;
                    @GripForce.started += instance.OnGripForce;
                    @GripForce.performed += instance.OnGripForce;
                    @GripForce.canceled += instance.OnGripForce;
                    @PrimaryButtonPressed.started += instance.OnPrimaryButtonPressed;
                    @PrimaryButtonPressed.performed += instance.OnPrimaryButtonPressed;
                    @PrimaryButtonPressed.canceled += instance.OnPrimaryButtonPressed;
                    @PrimaryButtonTouched.started += instance.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.performed += instance.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.canceled += instance.OnPrimaryButtonTouched;
                    @SecondaryButtonPressed.started += instance.OnSecondaryButtonPressed;
                    @SecondaryButtonPressed.performed += instance.OnSecondaryButtonPressed;
                    @SecondaryButtonPressed.canceled += instance.OnSecondaryButtonPressed;
                    @SecondaryButtonTouched.started += instance.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.performed += instance.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.canceled += instance.OnSecondaryButtonTouched;
                    @ThumbstickAxis.started += instance.OnThumbstickAxis;
                    @ThumbstickAxis.performed += instance.OnThumbstickAxis;
                    @ThumbstickAxis.canceled += instance.OnThumbstickAxis;
                    @ThumbstickPressed.started += instance.OnThumbstickPressed;
                    @ThumbstickPressed.performed += instance.OnThumbstickPressed;
                    @ThumbstickPressed.canceled += instance.OnThumbstickPressed;
                    @ThumbstickTouched.started += instance.OnThumbstickTouched;
                    @ThumbstickTouched.performed += instance.OnThumbstickTouched;
                    @ThumbstickTouched.canceled += instance.OnThumbstickTouched;
                    @TrackpadAxis.started += instance.OnTrackpadAxis;
                    @TrackpadAxis.performed += instance.OnTrackpadAxis;
                    @TrackpadAxis.canceled += instance.OnTrackpadAxis;
                    @TrackpadPressed.started += instance.OnTrackpadPressed;
                    @TrackpadPressed.performed += instance.OnTrackpadPressed;
                    @TrackpadPressed.canceled += instance.OnTrackpadPressed;
                    @TrackpadTouched.started += instance.OnTrackpadTouched;
                    @TrackpadTouched.performed += instance.OnTrackpadTouched;
                    @TrackpadTouched.canceled += instance.OnTrackpadTouched;
                }
            }
        }
        public ControllerLeftActions @ControllerLeft => new ControllerLeftActions(this);

        // ControllerRight
        private readonly InputActionMap m_ControllerRight;
        private IControllerRightActions m_ControllerRightActionsCallbackInterface;
        private readonly InputAction m_ControllerRight_TriggerAxis;
        private readonly InputAction m_ControllerRight_TriggerPressed;
        private readonly InputAction m_ControllerRight_GripAxis;
        private readonly InputAction m_ControllerRight_GripPressed;
        private readonly InputAction m_ControllerRight_GripForce;
        private readonly InputAction m_ControllerRight_PrimaryButtonPressed;
        private readonly InputAction m_ControllerRight_PrimaryButtonTouched;
        private readonly InputAction m_ControllerRight_SecondaryButtonPressed;
        private readonly InputAction m_ControllerRight_SecondaryButtonTouched;
        private readonly InputAction m_ControllerRight_ThumbstickAxis;
        private readonly InputAction m_ControllerRight_ThumbstickPressed;
        private readonly InputAction m_ControllerRight_ThumbstickTouched;
        private readonly InputAction m_ControllerRight_TrackpadAxis;
        private readonly InputAction m_ControllerRight_TrackpadPressed;
        private readonly InputAction m_ControllerRight_TrackpadTouched;
        public struct ControllerRightActions
        {
            private @XRInputActions m_Wrapper;
            public ControllerRightActions(@XRInputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @TriggerAxis => m_Wrapper.m_ControllerRight_TriggerAxis;
            public InputAction @TriggerPressed => m_Wrapper.m_ControllerRight_TriggerPressed;
            public InputAction @GripAxis => m_Wrapper.m_ControllerRight_GripAxis;
            public InputAction @GripPressed => m_Wrapper.m_ControllerRight_GripPressed;
            public InputAction @GripForce => m_Wrapper.m_ControllerRight_GripForce;
            public InputAction @PrimaryButtonPressed => m_Wrapper.m_ControllerRight_PrimaryButtonPressed;
            public InputAction @PrimaryButtonTouched => m_Wrapper.m_ControllerRight_PrimaryButtonTouched;
            public InputAction @SecondaryButtonPressed => m_Wrapper.m_ControllerRight_SecondaryButtonPressed;
            public InputAction @SecondaryButtonTouched => m_Wrapper.m_ControllerRight_SecondaryButtonTouched;
            public InputAction @ThumbstickAxis => m_Wrapper.m_ControllerRight_ThumbstickAxis;
            public InputAction @ThumbstickPressed => m_Wrapper.m_ControllerRight_ThumbstickPressed;
            public InputAction @ThumbstickTouched => m_Wrapper.m_ControllerRight_ThumbstickTouched;
            public InputAction @TrackpadAxis => m_Wrapper.m_ControllerRight_TrackpadAxis;
            public InputAction @TrackpadPressed => m_Wrapper.m_ControllerRight_TrackpadPressed;
            public InputAction @TrackpadTouched => m_Wrapper.m_ControllerRight_TrackpadTouched;
            public InputActionMap Get() { return m_Wrapper.m_ControllerRight; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(ControllerRightActions set) { return set.Get(); }
            public void SetCallbacks(IControllerRightActions instance)
            {
                if (m_Wrapper.m_ControllerRightActionsCallbackInterface != null)
                {
                    @TriggerAxis.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTriggerAxis;
                    @TriggerAxis.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTriggerAxis;
                    @TriggerAxis.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTriggerAxis;
                    @TriggerPressed.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTriggerPressed;
                    @TriggerPressed.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTriggerPressed;
                    @TriggerPressed.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTriggerPressed;
                    @GripAxis.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnGripAxis;
                    @GripAxis.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnGripAxis;
                    @GripAxis.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnGripAxis;
                    @GripPressed.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnGripPressed;
                    @GripPressed.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnGripPressed;
                    @GripPressed.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnGripPressed;
                    @GripForce.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnGripForce;
                    @GripForce.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnGripForce;
                    @GripForce.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnGripForce;
                    @PrimaryButtonPressed.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnPrimaryButtonPressed;
                    @PrimaryButtonPressed.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnPrimaryButtonPressed;
                    @PrimaryButtonPressed.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnPrimaryButtonPressed;
                    @PrimaryButtonTouched.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnPrimaryButtonTouched;
                    @SecondaryButtonPressed.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnSecondaryButtonPressed;
                    @SecondaryButtonPressed.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnSecondaryButtonPressed;
                    @SecondaryButtonPressed.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnSecondaryButtonPressed;
                    @SecondaryButtonTouched.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnSecondaryButtonTouched;
                    @ThumbstickAxis.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickAxis.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickAxis.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnThumbstickAxis;
                    @ThumbstickPressed.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnThumbstickPressed;
                    @ThumbstickPressed.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnThumbstickPressed;
                    @ThumbstickPressed.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnThumbstickPressed;
                    @ThumbstickTouched.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnThumbstickTouched;
                    @ThumbstickTouched.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnThumbstickTouched;
                    @ThumbstickTouched.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnThumbstickTouched;
                    @TrackpadAxis.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTrackpadAxis;
                    @TrackpadAxis.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTrackpadAxis;
                    @TrackpadAxis.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTrackpadAxis;
                    @TrackpadPressed.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTrackpadPressed;
                    @TrackpadPressed.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTrackpadPressed;
                    @TrackpadPressed.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTrackpadPressed;
                    @TrackpadTouched.started -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTrackpadTouched;
                    @TrackpadTouched.performed -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTrackpadTouched;
                    @TrackpadTouched.canceled -= m_Wrapper.m_ControllerRightActionsCallbackInterface.OnTrackpadTouched;
                }
                m_Wrapper.m_ControllerRightActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @TriggerAxis.started += instance.OnTriggerAxis;
                    @TriggerAxis.performed += instance.OnTriggerAxis;
                    @TriggerAxis.canceled += instance.OnTriggerAxis;
                    @TriggerPressed.started += instance.OnTriggerPressed;
                    @TriggerPressed.performed += instance.OnTriggerPressed;
                    @TriggerPressed.canceled += instance.OnTriggerPressed;
                    @GripAxis.started += instance.OnGripAxis;
                    @GripAxis.performed += instance.OnGripAxis;
                    @GripAxis.canceled += instance.OnGripAxis;
                    @GripPressed.started += instance.OnGripPressed;
                    @GripPressed.performed += instance.OnGripPressed;
                    @GripPressed.canceled += instance.OnGripPressed;
                    @GripForce.started += instance.OnGripForce;
                    @GripForce.performed += instance.OnGripForce;
                    @GripForce.canceled += instance.OnGripForce;
                    @PrimaryButtonPressed.started += instance.OnPrimaryButtonPressed;
                    @PrimaryButtonPressed.performed += instance.OnPrimaryButtonPressed;
                    @PrimaryButtonPressed.canceled += instance.OnPrimaryButtonPressed;
                    @PrimaryButtonTouched.started += instance.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.performed += instance.OnPrimaryButtonTouched;
                    @PrimaryButtonTouched.canceled += instance.OnPrimaryButtonTouched;
                    @SecondaryButtonPressed.started += instance.OnSecondaryButtonPressed;
                    @SecondaryButtonPressed.performed += instance.OnSecondaryButtonPressed;
                    @SecondaryButtonPressed.canceled += instance.OnSecondaryButtonPressed;
                    @SecondaryButtonTouched.started += instance.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.performed += instance.OnSecondaryButtonTouched;
                    @SecondaryButtonTouched.canceled += instance.OnSecondaryButtonTouched;
                    @ThumbstickAxis.started += instance.OnThumbstickAxis;
                    @ThumbstickAxis.performed += instance.OnThumbstickAxis;
                    @ThumbstickAxis.canceled += instance.OnThumbstickAxis;
                    @ThumbstickPressed.started += instance.OnThumbstickPressed;
                    @ThumbstickPressed.performed += instance.OnThumbstickPressed;
                    @ThumbstickPressed.canceled += instance.OnThumbstickPressed;
                    @ThumbstickTouched.started += instance.OnThumbstickTouched;
                    @ThumbstickTouched.performed += instance.OnThumbstickTouched;
                    @ThumbstickTouched.canceled += instance.OnThumbstickTouched;
                    @TrackpadAxis.started += instance.OnTrackpadAxis;
                    @TrackpadAxis.performed += instance.OnTrackpadAxis;
                    @TrackpadAxis.canceled += instance.OnTrackpadAxis;
                    @TrackpadPressed.started += instance.OnTrackpadPressed;
                    @TrackpadPressed.performed += instance.OnTrackpadPressed;
                    @TrackpadPressed.canceled += instance.OnTrackpadPressed;
                    @TrackpadTouched.started += instance.OnTrackpadTouched;
                    @TrackpadTouched.performed += instance.OnTrackpadTouched;
                    @TrackpadTouched.canceled += instance.OnTrackpadTouched;
                }
            }
        }
        public ControllerRightActions @ControllerRight => new ControllerRightActions(this);
        public interface IHMDActions
        {
            void OnCenterEyePosition(InputAction.CallbackContext context);
            void OnCenterEyeRotation(InputAction.CallbackContext context);
        }
        public interface IControllerLeftActions
        {
            void OnTriggerAxis(InputAction.CallbackContext context);
            void OnTriggerPressed(InputAction.CallbackContext context);
            void OnGripAxis(InputAction.CallbackContext context);
            void OnGripPressed(InputAction.CallbackContext context);
            void OnGripForce(InputAction.CallbackContext context);
            void OnPrimaryButtonPressed(InputAction.CallbackContext context);
            void OnPrimaryButtonTouched(InputAction.CallbackContext context);
            void OnSecondaryButtonPressed(InputAction.CallbackContext context);
            void OnSecondaryButtonTouched(InputAction.CallbackContext context);
            void OnThumbstickAxis(InputAction.CallbackContext context);
            void OnThumbstickPressed(InputAction.CallbackContext context);
            void OnThumbstickTouched(InputAction.CallbackContext context);
            void OnTrackpadAxis(InputAction.CallbackContext context);
            void OnTrackpadPressed(InputAction.CallbackContext context);
            void OnTrackpadTouched(InputAction.CallbackContext context);
        }
        public interface IControllerRightActions
        {
            void OnTriggerAxis(InputAction.CallbackContext context);
            void OnTriggerPressed(InputAction.CallbackContext context);
            void OnGripAxis(InputAction.CallbackContext context);
            void OnGripPressed(InputAction.CallbackContext context);
            void OnGripForce(InputAction.CallbackContext context);
            void OnPrimaryButtonPressed(InputAction.CallbackContext context);
            void OnPrimaryButtonTouched(InputAction.CallbackContext context);
            void OnSecondaryButtonPressed(InputAction.CallbackContext context);
            void OnSecondaryButtonTouched(InputAction.CallbackContext context);
            void OnThumbstickAxis(InputAction.CallbackContext context);
            void OnThumbstickPressed(InputAction.CallbackContext context);
            void OnThumbstickTouched(InputAction.CallbackContext context);
            void OnTrackpadAxis(InputAction.CallbackContext context);
            void OnTrackpadPressed(InputAction.CallbackContext context);
            void OnTrackpadTouched(InputAction.CallbackContext context);
        }
    }
}
